### ISSUE TITLE
feature request: add possibility to configure a ip adress

### ISSUE THREAD

**Issue by Micha-Btz** [grmasa/Open_light#1]
hi,

thanks for the app. the app is working well until I use the my normal firewall afwall app.
The discovery of the bulb isn't working with enabled firewall.
So it would be very nice to configure the ip address directly.

thanks Michael

**Comment by grmasa** [comment]
Hey,

I added the ability to change the IP address of a bulb by clicking the shown IP. 

I installed afwall+ but I can't replicate the problem. Can you provide more information?

**Comment by Micha-Btz** [comment]
Hi there,
I have two wlan networks at home 192.168.2.x from fritzbox for all devices and 192.168.4.x for all IoT devices on raspberry. The discovery only works, if I connect a phone with the wlan from the raspberry.
As far as I found out the discovery messages are not routed. If I test it with tcpdump, I don't get an answer.
Maybe it has nothing to do with the afwall and routing is the problem.

**Comment by Micha-Btz** [comment]
The solution is to set a route on the device with has the wlan, for me on my rasbpi.
https://blog.danman.eu/multicast-over-stupid-networks/
Then the discovery works.
