### ISSUE TITLE
Installation of v1.2 over v1.1.2 may not work.

### ISSUE THREAD

**Issue by OlegJktu** [grmasa/Open_light#4]
Installation of v1.2 over v1.1.2 may not work.
I tried installing v1.2 version of Open_light.apk over v1.1.2 version. Installation failed. After uninstalling version v1.1.2, the installation of v1.2 Open_light.apk was successful.

Возможно не работает установка версии v1.2 поверх версии v1.1.2 .
Я попробовал установить версию v1.2 Open_light.apk поверх версии v1.1.2 . Установка завершилась ошибкой. После удаления версии  v1.1.2 установка v1.2 Open_light.apk прошла удачно.

**Comment by grmasa** [comment]
Hey thanks for reporting! This happened because the previous releases were debug releases and the latest one isn't. Do you prefer debug releases?

**Comment by OlegJktu** [comment]
Clear.
I was just surprised by this installation situation.

Понятно. 
Я просто был удивлен такой ситуацией при установке.

**Comment by grmasa** [comment]
I changed the releases because some MIUI phones couldn't install them.
