### ISSUE TITLE
Lamp control does not work in version v1.2.

### ISSUE THREAD

**Issue by OlegJktu** [grmasa/Open_light#5]
Lamp control does not work in version v1.2.
Lamp control does not work in version 1.2. Lamps are marked as Offline after adding.
In v1.1.2, the lamp control works, the lamps are marked online.
Lamps model Yeelight light ceiling 1 YLXD01YL.

Не работает управление лампами в версии v1.2 .
Не работает управление лампами в версии 1.2. Лампы после добавления помечены как Offline.
В версии v1.1.2 управление лампами работает, лампы помечены online.
Модель светильников Yeelight light ceiling 1 YLXD01YL .

**Comment by grmasa** [comment]
I think this issue is related to #6

**Comment by OlegJktu** [comment]
> I think this issue is related to #6

These errors seem to be unrelated. In version 1.1.2 of the application, the lamp control works. And bug 6 is present in version 1.1.2.

> Думаю, эта проблема связана с №6

Кажется эти ошибки не связанны. В версии приложения 1.1.2 управление лампами работает. И баг №6 в версии 1.1.2 присутствует.

**Comment by OlegJktu** [comment]
I tested application versions 1.2.1 and 1.2.2. It is still not possible to control the lamps.

Я протестировал версии приложения  1.2.1 и 1.2.2. По прежнему не возможно управлять лампами.

**Comment by grmasa** [comment]
I cannot replicate this issue. Did you try to clear the application data? Also can you provide logs?
