### ISSUE TITLE
A random lamp is added instead of the one selected in the list.

### ISSUE THREAD

**Issue by OlegJktu** [grmasa/Open_light#6]
A random lamp is added instead of the one selected in the list.
I have a lot of Yeelight lamps. When trying to add a specific lamp (let's say 192.168.89.120) a random lamp is added (in my case 192.168.89.152).

Добавляется случайная лампа вместо выбранной в списке.
У меня много ламп Yeelight. При попытке добавить конкретную лампу (допустим 192.168.89.120) добавляется случайная лампа (в моем случае 192.168.89.152).

![creenrecorder-2020-10-26-10-24-59-17](https://user-images.githubusercontent.com/34140076/97150476-10bf2f00-1766-11eb-9f17-ae7d7a8b52d0.gif)

**Comment by grmasa** [comment]
I only have one lamp but I am positive that this issue is fixed by v1.2.1.

**Comment by OlegJktu** [comment]
Perfectly!
I tested 1.2.1 and 1.2.2 now the selected lump is added.
Thanks.
Прекрасно!
Я протестировал 1.2.1 и 1.2.2 теперь добавляется выбранная лапмпа.
Спасибо.
